### ISSUE TITLE
Add Google Analytics to track usage

### ISSUE THREAD

**Issue by brettcannon** [Which-Film/which-film.info#11]
Make sure to also capture details such as number of usernames entered, whether the site is used, how many movies listed, clicks on movies, etc.

**Comment by brettcannon** [comment]
http://googledevelopers.blogspot.com/2016/02/introducing-autotrack-for-analyticsjs.html

**Comment by brettcannon** [comment]
https://www.google.com/analytics/standard/

**Comment by brettcannon** [comment]
Dart library for interacting w/ Google Analytics: https://pub.dartlang.org/packages/usage

**Comment by kschmidtdev** [comment]
@brettcannon 

> Note: This library is intended for use with the Google Analytics application / mobile app style tracking IDs (as opposed to the web site style tracking IDs).

Do we want app style tracking or web site style tracking?

**Comment by brettcannon** [comment]
I don't even know what the difference is. :) I assume its page interactions vs referrals in terms of trade-offs?

**Comment by kschmidtdev** [comment]
Just this from the docs:

> Your application should provide an opt-in option for the user. If they opt-in, set the optIn field to true. This setting will persist across sessions automatically.

I get the feeling with the web one it's just always on, or it obeys the user's global opt-out cookie if they have one?
