### ISSUE TITLE
Support N users

### ISSUE THREAD

**Issue by brettcannon** [Which-Film/which-film.info#33]
Instead of only supporting 1-4 users with static boxes.

**Comment by kschmidtdev** [comment]
I forgot - the plan is to initially have a single input box, then an add button, and when you type in a username, then press add, the input box is cleared and the user is added to a label below - right?

**Comment by brettcannon** [comment]
Yep, although I'm not sure  what you mean by label. Do you mean a list because that's what I thought we were doing; splitting the screen below the input box into two columns w/ one for usernames and the other  for  the list of movies?

Although that does give me an idea for sharing how a movie got on to the list; coloured labels below each movie, where each colour represents a person. We can then add a label for each person that says how they contributed to the movie, but coloured to match the person. So for someone who got a movie to show up because of an 8 rating, the movie would have a label of "8★" and have it coloured to match the person's randomly assigned colour (this would all be instead of the "lines from name to movies" idea I have brought up previously).
