### ISSUE TITLE
Dependency issue?

### ISSUE THREAD

**Issue by kschmidtdev** [Which-Film/which-film.info#34]
I just pulled master, and when I run `pub get`, I get this:

> Package test has no versions that match >=0.12.10+2 <0.13.0 derived from:
> - which_film depends on version ^0.12.10+2

Not sure how it was working on your machine last night? I tried deleting the packages folder, as well as running `pub upgrade -n`, but I get the same message.

**Comment by brettcannon** [comment]
https://pub.dartlang.org/packages/test shows that `^0.12.10+2` is the current version.

**Comment by brettcannon** [comment]
You could either try specifying the version in a different way -- e.g., `>=0.12.0 <0.13.0` or leave out the version specification temporarily to see what version it grabs.

**Comment by brettcannon** [comment]
Oh, and are you running the latest version of Dart?

**Comment by kschmidtdev** [comment]
Nope, wasn't running the latest dart. No issues after updating.
